//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Orders struct {
	ID           uuid.UUID `sql:"primary_key"`
	Type         string
	SellCurrency string
	SellQuantity *float64
	SellAddress  string
	SellUserID   string
	Price        float64
	BuyCurrency  string
	BuyQuantity  *float64
	BuyAddress   string
	BuyUserID    string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	RemovedAt    *time.Time
	ClosedAt     *time.Time
}
