//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Transactions struct {
	ID              uuid.UUID `sql:"primary_key"`
	SenderAddress   string
	SenderUserID    string
	ReceiverAddress string
	ReceiverUserID  string
	Amount          float64
	Currency        string
	Purpose         *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
