//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Wallets struct {
	Address   string `sql:"primary_key"`
	UserID    string
	Currency  string
	Balance   float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
